# Generated by Django 4.2.26 on 2025-11-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Особенность')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.CreateModel(
            name='HouseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ЧПУ (URL)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена (₽)')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Общая площадь, м²')),
                ('area_garage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь навеса для авто, м²')),
                ('area_terrace', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь крытой террасы, м²')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Спальни')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Санузлы')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('main_image', models.ImageField(upload_to='projects/main/', verbose_name='Главное изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(blank=True, to='projects.feature', verbose_name='Особенности')),
            ],
            options={
                'verbose_name': 'Проект дома',
                'verbose_name_plural': 'Проекты домов',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название плана (например: Фасад, План 1 этажа)')),
                ('image', models.ImageField(upload_to='projects/plans/', verbose_name='Изображение плана')),
                ('is_main', models.BooleanField(default=False, verbose_name='Отображать в галерее планов')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.houseproject', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'План/Фасад проекта',
                'verbose_name_plural': 'Планы/Фасады проектов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение в галерее')),
                ('image_type', models.CharField(choices=[('gallery', 'Галерея'), ('plan', 'План/Фасад')], default='gallery', max_length=20, verbose_name='Тип изображения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.houseproject', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проектов',
            },
        ),
        migrations.AddField(
            model_name='houseproject',
            name='materials',
            field=models.ManyToManyField(blank=True, to='projects.material', verbose_name='Материалы'),
        ),
        migrations.CreateModel(
            name='ConstructionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost_frame', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Каркас')),
                ('cost_gasconcrete', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Газобетон')),
                ('cost_brick', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Кирпич')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.houseproject')),
            ],
            options={
                'verbose_name': 'Этап строительства',
                'verbose_name_plural': 'Этапы строительства',
                'ordering': ['order'],
            },
        ),
    ]
