# Generated by Django 4.2.25 on 2025-10-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseproject',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True, verbose_name='ЧПУ (URL)'),
            preserve_default=False,
        ),
    ]
