# Generated by Django 5.2.3 on 2025-11-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный этап')),
                ('price_coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Используется только для необязательных этапов', max_digits=5, verbose_name='Коэффициент цены')),
            ],
        ),
    ]
