# Generated by Django 5.2.3 on 2025-11-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Обязательный этап'),
        ),
    ]
