# Generated by Django 5.2.3 on 2025-10-10 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_houseproject_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost_frame', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Каркас')),
                ('cost_gasconcrete', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Газобетон')),
                ('cost_brick', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Кирпич')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.houseproject')),
            ],
            options={
                'verbose_name': 'Этап строительства',
                'verbose_name_plural': 'Этапы строительства',
                'ordering': ['order'],
            },
        ),
    ]
