# Generated by Django 5.2.3 on 2025-10-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_constructionstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название плана (например: Фасад, План 1 этажа)')),
                ('image', models.ImageField(upload_to='projects/plans/', verbose_name='Изображение плана')),
                ('is_main', models.BooleanField(default=False, verbose_name='Отображать в галерее планов')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.houseproject', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'План/Фасад проекта',
                'verbose_name_plural': 'Планы/Фасады проектов',
                'ordering': ['order'],
            },
        ),
    ]
