# Generated by Django 5.2.3 on 2025-11-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_stage_constructionstage_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionstage',
            name='cost_brick',
        ),
        migrations.RemoveField(
            model_name='constructionstage',
            name='cost_frame',
        ),
        migrations.RemoveField(
            model_name='constructionstage',
            name='cost_gasconcrete',
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='cost_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за 1 м² (₽)'),
        ),
    ]
