# Generated by Django 5.2.3 on 2025-10-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='image_type',
            field=models.CharField(choices=[('gallery', 'Галерея'), ('plan', 'План/Фасад')], default='gallery', max_length=20, verbose_name='Тип изображения'),
        ),
    ]
