# Generated by Django 5.2.3 on 2025-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_houseproject_stages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
        migrations.AddField(
            model_name='stage',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая стоимость этапа'),
        ),
    ]
