# Generated by Django 5.2.3 on 2025-11-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_stage_options_stage_cost_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='cost_brick',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='cost_frame',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='cost_gasconcrete',
        ),
        migrations.AddField(
            model_name='stage',
            name='cost_per_m2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Используется для необязательных этапов (умножается на площадь и технологию)', max_digits=8, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Используется для обязательных этапов', max_digits=12, verbose_name='Общая стоимость (фиксированная)'),
        ),
    ]
