# Generated by Django 5.2.3 on 2025-11-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_stage_cost_brick_remove_stage_cost_frame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='cost_total',
        ),
        migrations.AlterField(
            model_name='stage',
            name='cost_per_m2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена за м² для необязательных этапов', max_digits=8, verbose_name='Цена за м²'),
        ),
    ]
