# Generated by Django 5.2.3 on 2025-11-09 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название техники')),
                ('capacity', models.FloatField(help_text='в тоннах или л.с.', verbose_name='Грузоподъёмность/Мощность')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Фото')),
                ('specs', models.JSONField(blank=True, help_text='Например: {"Длина стрелы": "30 м", "Вылет стрелы": "25 м"}', null=True, verbose_name='Дополнительные характеристики')),
            ],
            options={
                'verbose_name': 'Единица техники',
                'verbose_name_plural': 'Техника',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Типы техники',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Общая площадь')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Срок выполнения (месяцы)')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена')),
                ('style', models.CharField(blank=True, max_length=100, verbose_name='Стиль')),
                ('main_image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Главное изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipment/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.equipment', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Изображение техники',
                'verbose_name_plural': 'Изображения техники',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.equipmenttype', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок секции')),
                ('description', models.TextField(blank=True, verbose_name='Описание секции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='services.project')),
            ],
            options={
                'verbose_name': 'Секция проекта',
                'verbose_name_plural': 'Секции проекта',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/sections/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.projectsection')),
            ],
            options={
                'verbose_name': 'Изображение секции',
                'verbose_name_plural': 'Изображения секций',
                'ordering': ['order'],
            },
        ),
    ]
