# Generated by Django 4.2.25 on 2025-10-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='specs',
            field=models.JSONField(blank=True, help_text='Например: {"Длина стрелы": "30 м", "Вылет стрелы": "25 м"}', null=True, verbose_name='Дополнительные характеристики'),
        ),
    ]
