# Generated by Django 5.2.3 on 2025-11-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='design_type',
            field=models.CharField(choices=[('interior', 'Интерьерный дизайн'), ('landscape', 'Ландшафтный дизайн')], default='interior', max_length=20, verbose_name='Тип дизайна'),
        ),
    ]
