# Generated by Django 5.2.3 on 2025-11-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_project_design_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='design_type',
        ),
        migrations.AddField(
            model_name='project',
            name='service_type',
            field=models.CharField(choices=[('interior', 'Интерьерный дизайн'), ('landscape', 'Ландшафтный дизайн')], default='interior', max_length=20, verbose_name='Тип услуги'),
        ),
    ]
