# Generated by Django 4.2.25 on 2025-10-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_project_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок секции')),
                ('description', models.TextField(blank=True, verbose_name='Описание секции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Секция проекта',
                'verbose_name_plural': 'Секции проекта',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/sections/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.projectsection')),
            ],
            options={
                'verbose_name': 'Изображение секции',
                'verbose_name_plural': 'Изображения секций',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Общая площадь'),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок выполнения (месяцы)'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='projects/', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='project',
            name='style',
            field=models.CharField(blank=True, max_length=100, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.AddField(
            model_name='projectsection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='services.project'),
        ),
    ]
